/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.10 public/models/calculator/model.gltf 
*/

import React, { useRef } from "react";
import { useGLTF, OrthographicCamera } from "@react-three/drei";

export function Calculator({ calculatorRef, ...props }) {
  const { nodes, materials } = useGLTF("./models/calculator/model.gltf");
  return (
    <group {...props} dispose={null}>
      <group scale={0.01}>
        <group
          ref={calculatorRef}
          position={[15.869, 126.056, 0]}
          rotation={[-Math.PI / 2, 0, 0]}
        >
          <mesh
            geometry={nodes.Text_3.geometry}
            material={nodes.Text_3.material}
            position={[-222.608, -9.619, 50.944]}
          />
          <mesh
            geometry={nodes.Text_4.geometry}
            material={nodes.Text_4.material}
            position={[-396.15, -40.376, 50.944]}
          />
          <mesh
            geometry={nodes.Text_15.geometry}
            material={nodes.Text_15.material}
            position={[-161.697, -194.905, 50.944]}
          />
          <mesh
            geometry={nodes.Text_5.geometry}
            material={nodes.Text_5.material}
            position={[-9.204, 87.582, 50.944]}
          />
          <mesh
            geometry={nodes.Text_7.geometry}
            material={nodes.Text_7.material}
            position={[199.327, -4.117, 50.944]}
          />
          <mesh
            geometry={nodes.Text_16.geometry}
            material={nodes.Text_16.material}
            position={[-499.393, -196.05, 50.944]}
          />
          <mesh
            geometry={nodes.Text_6.geometry}
            material={nodes.Text_6.material}
            position={[-561.653, -4.117, 50.944]}
          />
          <mesh
            geometry={nodes.Text_11.geometry}
            material={nodes.Text_11.material}
            position={[406.318, -5.537, 50.944]}
          />
          <mesh
            geometry={nodes.Text_10.geometry}
            material={nodes.Text_10.material}
            position={[615.104, -5.537, 50.944]}
          />
          <mesh
            geometry={nodes.Text_13.geometry}
            material={nodes.Text_13.material}
            position={[321.527, -195.776, 50.944]}
          />
          <mesh
            geometry={nodes.Text_12.geometry}
            material={nodes.Text_12.material}
            position={[575.648, -195.776, 50.944]}
          />
          <mesh
            geometry={nodes.Text_9.geometry}
            material={nodes.Text_9.material}
            position={[615.104, 190, 50.944]}
          />
          <mesh
            geometry={nodes.Text_14.geometry}
            material={nodes.Text_14.material}
            position={[116.814, -203.468, 50.944]}
          />
          <mesh
            geometry={nodes.Text_8.geometry}
            material={nodes.Text_8.material}
            position={[301.435, 190, 50.944]}
          />
          <mesh
            geometry={nodes.Text_2.geometry}
            material={nodes.Text_2.material}
            position={[-209.446, 190, 50.944]}
          />
          <mesh
            geometry={nodes.Text.geometry}
            material={nodes.Text.material}
            position={[-491.869, 190, 50.944]}
          />
          <mesh
            geometry={nodes.Shape_3.geometry}
            material={nodes.Shape_3.material}
            position={[-693.79, 79.225, 0]}
          />
          <mesh
            geometry={nodes.Shape_2.geometry}
            material={nodes.Shape_2.material}
            position={[-445.883, -18.842, 0]}
          />
          <mesh
            geometry={nodes.Shape_8.geometry}
            material={nodes.Shape_8.material}
            position={[119.495, 267.806, 0]}
          />
          <mesh
            geometry={nodes.Shape_7.geometry}
            material={nodes.Shape_7.material}
            position={[-87.037, 264.42, 0]}
          />
          <mesh
            geometry={nodes.Shape_13.geometry}
            material={nodes.Shape_13.material}
            position={[451.263, -119.685, 0]}
          />
          <mesh
            geometry={nodes.Shape_12.geometry}
            material={nodes.Shape_12.material}
            position={[533.383, 73.315, 0]}
          />
          <mesh
            geometry={nodes.Shape_13_1.geometry}
            material={nodes.Shape_13_1.material}
            position={[243.883, -119.685, 0]}
          />
          <mesh
            geometry={nodes.Shape_14.geometry}
            material={nodes.Shape_14.material}
            position={[-320.75, -119.685, 0]}
          />
          <mesh
            geometry={nodes.Shape_15.geometry}
            material={nodes.Shape_15.material}
            position={[-641.314, -119.685, 0]}
          />
          <mesh
            geometry={nodes.Shape_13_2.geometry}
            material={nodes.Shape_13_2.material}
            position={[37.883, -119.685, 0]}
          />
          <mesh
            geometry={nodes.Shape_11.geometry}
            material={nodes.Shape_11.material}
            position={[532.383, 267.947, 0]}
          />
          <mesh
            geometry={nodes.Shape_9.geometry}
            material={nodes.Shape_9.material}
            position={[119.383, 73.315, 0]}
          />
          <mesh
            geometry={nodes.Shape_6.geometry}
            material={nodes.Shape_6.material}
            position={[-291.248, 267.947, 0]}
          />
          <mesh
            geometry={nodes.Shape_5.geometry}
            material={nodes.Shape_5.material}
            position={[-641.099, 267.947, 0]}
          />
          <mesh
            geometry={nodes.Shape_4.geometry}
            material={nodes.Shape_4.material}
            position={[-640.549, 73.315, 0]}
          />
          <mesh
            geometry={nodes.Shape.geometry}
            material={nodes.Shape.material}
            position={[-445.364, 73.315, 0]}
          />
        </group>
        {/* <OrthographicCamera
          makeDefault={false}
          far={50000}
          near={50}
          position={[-515.825, 337.363, 828.293]}
          rotation={[-0.643, -0.49, -0.339]}
        /> */}
        <directionalLight
          intensity={0.75}
          decay={2}
          rotation={[2.315, -0.618, -1.081]}
        />
        {/* <OrthographicCamera
          makeDefault={false}
          far={50000}
          near={0}
          position={[58.092, 999.166, 56.402]}
          rotation={[-1.553, 0, 0]}
        />
        <OrthographicCamera
          makeDefault={false}
          far={100000}
          near={0}
          position={[-348.91, 704.76, 578.144]}
          rotation={[-0.802, -0.434, -0.41]}
        /> */}

        {/* FLOOR */}
        {/* <mesh
          geometry={nodes.Floor.geometry}
          material={nodes.Floor.material}
          position={[21, 137.444, 28.813]}
          rotation={[-1.553, 0, 0]}
        /> */}
      </group>
    </group>
  );
}

useGLTF.preload("./models/calculator/model.gltf");
