/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.10 public/models/calculadora/model.gltf 
*/

import React, { useRef } from "react";
import { useGLTF, PerspectiveCamera } from "@react-three/drei";

export function Keyboard({ calculatorRef, ...props }) {
  const { nodes, materials } = useGLTF("./models/keyboard/model.gltf");
  return (
    <group {...props} dispose={null}>
      <group scale={0.01}>
        <group ref={calculatorRef} position={[-209.773, -18.858, 990.665]}>
          <group
            value="CE"
            type="clear"
            position={[-189.567, 38.858, -252.935]}
            scale={[1.009, 1, 1]}
          >
            <mesh
              geometry={nodes["Text-ABC"].geometry}
              position={[59.054, 44, 0.405]}
              rotation={[-Math.PI / 2, 0, 0]}
            >
              <meshStandardMaterial color="white" />
            </mesh>
            <mesh
              geometry={nodes["key-base"].geometry}
              position={[-0.93, -1.985, 0]}
            >
              <meshStandardMaterial color="green" />
            </mesh>
          </group>

          <group
            value="="
            type="submit"
            position={[188.163, 38.858, 250.449]}
            rotation={[0, Math.PI / 2, 0]}
            scale={[1.015, 1, 1]}
          >
            <mesh
              geometry={nodes["key-base_1"].geometry}
              material={nodes["key-base_1"].material}
              position={[-0.934, -1.985, 0]}
            >
              <meshStandardMaterial color="#A54450" />
            </mesh>
            <mesh
              geometry={nodes["Text-ABC_1"].geometry}
              material={nodes["Text-ABC_1"].material}
              position={[59.054, 44, 0.405]}
              rotation={[-Math.PI / 2, 0, -Math.PI / 2]}
            >
              <meshStandardMaterial color="#404040" />
            </mesh>
          </group>

          <group
            value="0"
            type="number"
            position={[-188.987, 38.858, 251.365]}
            scale={[1.009, 1, 1]}
          >
            <mesh
              geometry={nodes["key-base_2"].geometry}
              material={nodes["key-base_2"].material}
              position={[-0.934, -1.985, 0]}
            >
              <meshStandardMaterial color="#E3E3E3" />
            </mesh>
            <mesh
              geometry={nodes["Text-ABC_2"].geometry}
              material={nodes["Text-ABC_2"].material}
              position={[59.054, 44, 0.405]}
              rotation={[-Math.PI / 2, 0, 0]}
            >
              <meshStandardMaterial color="#404040" />
            </mesh>
          </group>
          <group value="." type="point" position={[62.671, 38.858, 251.365]}>
            <mesh
              geometry={nodes["Text-ABC_3"].geometry}
              material={nodes["Text-ABC_3"].material}
              position={[-2.794, 40.441, 0.577]}
              rotation={[-Math.PI / 2, 0, 0]}
            >
              <meshStandardMaterial color="#404040" />
            </mesh>
            <mesh
              geometry={nodes["key-base_3"].geometry}
              material={nodes["key-base_3"].material}
              position={[-0.934, -1.985, 0]}
            >
              <meshStandardMaterial color="#E3E3E3" />
            </mesh>
          </group>
          <group value="*" type="operation" position={[188.163, 38.858, 0.283]}>
            <mesh
              geometry={nodes["Text-ABC_4"].geometry}
              material={nodes["Text-ABC_4"].material}
              position={[-2.794, 40.441, 0.577]}
              rotation={[-Math.PI / 2, 0, 0]}
            >
              <meshStandardMaterial color="#404040" />
            </mesh>
            <mesh
              geometry={nodes["key-base_4"].geometry}
              material={nodes["key-base_4"].material}
              position={[-0.934, -1.985, 0]}
            >
              <meshStandardMaterial color="#E3E3E3" />
            </mesh>
          </group>
          <group value="3" type="number" position={[62.671, 38.858, 124.775]}>
            <mesh
              geometry={nodes["key-base_5"].geometry}
              material={nodes["key-base_5"].material}
              position={[-0.934, -1.985, 0]}
            >
              <meshStandardMaterial color="#E3E3E3" />
            </mesh>
            <mesh
              geometry={nodes["Text-ABC_5"].geometry}
              material={nodes["Text-ABC_5"].material}
              position={[-2.794, 40.441, 0.577]}
              rotation={[-Math.PI / 2, 0, 0]}
            >
              <meshStandardMaterial color="#404040" />
            </mesh>
          </group>
          <group value="6" type="number" position={[62.671, 38.858, 0.283]}>
            <mesh
              geometry={nodes["key-base_6"].geometry}
              material={nodes["key-base_6"].material}
              position={[-0.934, -1.985, 0]}
            >
              <meshStandardMaterial color="#E3E3E3" />
            </mesh>
            <mesh
              geometry={nodes["Text-ABC_6"].geometry}
              material={nodes["Text-ABC_6"].material}
              position={[-2.794, 40.441, 0.577]}
              rotation={[-Math.PI / 2, 0, 0]}
            >
              <meshStandardMaterial color="#404040" />
            </mesh>
          </group>
          <group value="2" type="number" position={[-64.077, 38.858, 125.773]}>
            <mesh
              geometry={nodes["key-base_7"].geometry}
              material={nodes["key-base_7"].material}
              position={[-0.934, -1.985, 0]}
            >
              <meshStandardMaterial color="#E3E3E3" />
            </mesh>
            <mesh
              geometry={nodes["Text-ABC_7"].geometry}
              material={nodes["Text-ABC_7"].material}
              position={[-2.794, 40.441, 0.577]}
              rotation={[-Math.PI / 2, 0, 0]}
            >
              <meshStandardMaterial color="#404040" />
            </mesh>
          </group>
          <group value="5" type="number" position={[-64.077, 38.858, 0.283]}>
            <mesh
              geometry={nodes["Text-ABC_8"].geometry}
              material={nodes["Text-ABC_8"].material}
              position={[-2.794, 40.441, 0.577]}
              rotation={[-Math.PI / 2, 0, 0]}
            >
              <meshStandardMaterial color="#404040" />
            </mesh>
            <mesh
              geometry={nodes["key-base_8"].geometry}
              material={nodes["key-base_8"].material}
              position={[-0.934, -1.985, 0]}
            >
              <meshStandardMaterial color="#E3E3E3" />
            </mesh>
          </group>
          <group value="1" type="number" position={[-189.567, 38.858, 124.775]}>
            <mesh
              geometry={nodes["key-base_9"].geometry}
              material={nodes["key-base_9"].material}
              position={[-0.93, -1.985, 0]}
            >
              <meshStandardMaterial color="#E3E3E3" />
            </mesh>
            <mesh
              geometry={nodes["Text-ABC_9"].geometry}
              material={nodes["Text-ABC_9"].material}
              position={[-2.794, 40.441, 0.577]}
              rotation={[-Math.PI / 2, 0, 0]}
            >
              <meshStandardMaterial color="#404040" />
            </mesh>
          </group>
          <group value="4" type="number" position={[-189.567, 38.858, 0.283]}>
            <mesh
              geometry={nodes["key-base_10"].geometry}
              material={nodes["key-base_10"].material}
              position={[-0.934, -1.985, 0]}
            >
              <meshStandardMaterial color="#E3E3E3" />
            </mesh>
            <mesh
              geometry={nodes["Text-ABC_10"].geometry}
              material={nodes["Text-ABC_10"].material}
              position={[-2.794, 40.441, 0.577]}
              rotation={[-Math.PI / 2, 0, 0]}
            >
              <meshStandardMaterial color="#404040" />
            </mesh>
          </group>
          <group value="/" type="operation" position={[188.161, 38.858, -127.445]}>
            <mesh
              geometry={nodes["key-base_11"].geometry}
              material={nodes["key-base_11"].material}
              position={[-0.934, -1.985, 0]}
            >
              <meshStandardMaterial color="#E3E3E3" />
            </mesh>
            <mesh
              geometry={nodes["Text-ABC_11"].geometry}
              material={nodes["Text-ABC_11"].material}
              position={[-2.794, 40.441, 0.577]}
              rotation={[-Math.PI / 2, 0, 0]}
            >
              <meshStandardMaterial color="#404040" />
            </mesh>
          </group>
          <group value="-" type="operation" position={[188.163, 38.858, -252.935]}>
            <mesh
              geometry={nodes["key-base_12"].geometry}
              material={nodes["key-base_12"].material}
              position={[-0.934, -1.985, 0]}
            >
              <meshStandardMaterial color="#E3E3E3" />
            </mesh>
            <mesh
              geometry={nodes["Text-ABC_12"].geometry}
              material={nodes["Text-ABC_12"].material}
              position={[-2.794, 40.441, 0.577]}
              rotation={[-Math.PI / 2, 0, 0]}
            >
              <meshStandardMaterial color="#404040" />
            </mesh>
          </group>
          <group value="9" type="number" position={[62.671, 38.858, -128.445]}>
            <mesh
              geometry={nodes["key-base_13"].geometry}
              material={nodes["key-base_13"].material}
              position={[-0.934, -1.985, 0]}
            >
              <meshStandardMaterial color="#E3E3E3" />
            </mesh>
            <mesh
              geometry={nodes["Text-ABC_13"].geometry}
              material={nodes["Text-ABC_13"].material}
              position={[-2.794, 40.441, 0.577]}
              rotation={[-Math.PI / 2, 0, 0]}
            >
              <meshStandardMaterial color="#404040" />
            </mesh>
          </group>
          <group value="+" type="operation" position={[62.671, 38.858, -252.935]}>
            <mesh
              geometry={nodes["key-base_14"].geometry}
              material={nodes["key-base_14"].material}
              position={[-0.934, -1.985, 0]}
            >
              <meshStandardMaterial color="#E3E3E3" />
            </mesh>
            <mesh
              geometry={nodes["Text-ABC_14"].geometry}
              material={nodes["Text-ABC_14"].material}
              position={[-2.794, 40.441, 0.577]}
              rotation={[-Math.PI / 2, 0, 0]}
            >
              <meshStandardMaterial color="#404040" />
            </mesh>
          </group>
          <group value="8" type="number" position={[-64.077, 38.858, -127.445]}>
            <mesh
              geometry={nodes["key-base_15"].geometry}
              material={nodes["key-base_15"].material}
              position={[-0.934, -1.985, 0]}
            >
              <meshStandardMaterial color="#E3E3E3" />
            </mesh>
            <mesh
              geometry={nodes["Text-ABC_15"].geometry}
              material={nodes["Text-ABC_15"].material}
              position={[-2.794, 40.441, 0.577]}
              rotation={[-Math.PI / 2, 0, 0]}
            >
              <meshStandardMaterial color="#404040" />
            </mesh>
          </group>
          <group value="7" type="number" position={[-189.567, 38.858, -128.445]}>
            <mesh
              geometry={nodes["key-base_16"].geometry}
              material={nodes["key-base_16"].material}
              position={[-0.934, -1.985, 0]}
            >
              <meshStandardMaterial color="#E3E3E3" />
            </mesh>
            <mesh
              geometry={nodes["Text-ABC_16"].geometry}
              material={nodes["Text-ABC_16"].material}
              position={[-2.794, 40.441, 0.577]}
              rotation={[-Math.PI / 2, 0, 0]}
            >
              <meshStandardMaterial color="#404040" />
            </mesh>
          </group>
          <group nonClickable>
            <mesh
              geometry={nodes.base.geometry}
              material={nodes.base.material}
              position={[0, 0.718, 0]}
              rotation={[-Math.PI / 2, 0, 0]}
            >
              <meshStandardMaterial color="#525252" />
            </mesh>
          </group>
        </group>
        <PerspectiveCamera
          makeDefault={false}
          far={100000}
          near={5}
          fov={45}
          position={[-657.555, 1372.225, 1963.291]}
          rotation={[-0.994, -0.212, -0.313]}
        />
      </group>
    </group>
  );
}

useGLTF.preload("./models/keyboard/model.gltf");
